[package]
name = "bwterraingen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bwmap = { git = "ssh://git@github.com/zzlk/bwmap.git" }

multimap = "*"
rand = "*"

anyhow = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["registry", "env-filter"] }
tracing-log = "*"
console-subscriber = "*"
